### ISSUE TITLE
Update co-creators logos + links

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/cphtechfest.org#20]

**Comment by christoffermalling** [comment]
Her slices af en logocollage til sitet. 
Hvis du hellere vil have filerne på en anden måde, eller i en anden størrelse, må du lige give mig besked, så laver jeg det om.

**href** 

Sponsor 1: http://www.momondo.dk/
Sponsor 2: https://www.twentythree.net/
Sponsor 3: http://siteimprove.com/
Sponsor 4: https://tradeshift.com/
Sponsor 5: https://unity3d.com/
Sponsor 6: https://www.zendesk.com/

![sponsor_collage_website_01](https://cloud.githubusercontent.com/assets/20956269/17658270/d0d59400-62ca-11e6-9832-709abb3717bf.png)
![sponsor_collage_website_02](https://cloud.githubusercontent.com/assets/20956269/17658271/d0eca0dc-62ca-11e6-9285-fa4417baf6f5.png)
![sponsor_collage_website_03](https://cloud.githubusercontent.com/assets/20956269/17658273/d0f4c348-62ca-11e6-9907-2344cf31e068.png)
![sponsor_collage_website_04](https://cloud.githubusercontent.com/assets/20956269/17658275/d0f666c6-62ca-11e6-8544-3c88ea3759ba.png)
![sponsor_collage_website_05](https://cloud.githubusercontent.com/assets/20956269/17658274/d0f4e85a-62ca-11e6-844b-b5084cd9cdeb.png)
![sponsor_collage_website_06](https://cloud.githubusercontent.com/assets/20956269/17658272/d0f3671e-62ca-11e6-8df6-37ee8095caf8.png)
