### ISSUE TITLE
Update small social media icons

### ISSUE THREAD

**Issue by christoffermalling** [auchenberg/cphtechfest.org#22]
Please update with these icons

![medium_67x67](https://cloud.githubusercontent.com/assets/20956269/17692063/3058553e-6398-11e6-9192-22d61b86e2c5.png)
![instagram_67x67](https://cloud.githubusercontent.com/assets/20956269/17692062/30573c6c-6398-11e6-8e6f-4bcf1cb381c5.png)
![twitter_67x67](https://cloud.githubusercontent.com/assets/20956269/17692065/305c47de-6398-11e6-9c56-bcd0338aa21a.png)
![facebook_67x67](https://cloud.githubusercontent.com/assets/20956269/17692064/305bb68e-6398-11e6-9f75-74e66bb72595.png)

**Comment by auchenberg** [comment]
Jeg skal bruge ikonerne i SVG format, @christoffermalling

**Comment by christoffermalling** [comment]
Jeg kan ikke paste dem direkte her i github, så du får dem som shared links fra drive.

https://drive.google.com/file/d/0B76UfTgMf6WiSkY3M0tLTE1kVUk/view?usp=sharing
https://drive.google.com/file/d/0B76UfTgMf6WiMF9WUU0tbEhGVnM/view?usp=sharing
https://drive.google.com/file/d/0B76UfTgMf6WiZl91clNTMzZZOHM/view?usp=sharing
https://drive.google.com/file/d/0B76UfTgMf6WiRk5FamRickxHRTg/view?usp=sharing
