### ISSUE TITLE
Add image for social media previews

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/cphtechfest.org#25]
See https://developers.facebook.com/docs/sharing/best-practices/#images

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

Please add the image as `img/social.png`

**Comment by christoffermalling** [comment]
Done! Added img/social.png

**Comment by auchenberg** [comment]
![sharing debugger - facebook for developers 2016-08-17 10-27-22](https://cloud.githubusercontent.com/assets/173559/17746519/363d48c4-6465-11e6-8daa-eaeddb31a608.png)

Image is too big.

**Comment by auchenberg** [comment]
![card validator twitter developers 2016-08-17 10-33-44](https://cloud.githubusercontent.com/assets/173559/17746688/1ac2feda-6466-11e6-9bc5-3fb443dd26fa.png)

Twitter looks good.

**Comment by christoffermalling** [comment]
Thanks! 
The picture is only 32.6 KB, so that shouldn't be the case. Want me to try a jpg or something instead?

**Comment by auchenberg** [comment]
Looks good now, https://developers.facebook.com/tools/debug/sharing/?q=http%3A%2F%2Fcphtechfest.org%2F
