### ISSUE TITLE
Make newsletter functionality work

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/cphtechfest.org#26]
We should sign up in Mailchimp or something?

**Comment by christoffermalling** [comment]
Vi vil gerne have at den skriver folk op på en mailchimp liste.

Jeg er ikke sikker på hvad du skal bruge fra mailchimp, for at få funktionaliteten til at virke. Her er det kode de giver os fra "Embed signup form". Kan du bruge det, ellers sig til, så finder jeg hvad du skal bruge. Brug gerne den styling du allerede har lavet, og ignorer det mailchimp har lavet.



<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">

<style type="text/css">
    #mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; }
    /* Add your own MailChimp form style overrides in your site stylesheet or in this style block.
       We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<div id="mc_embed_signup">
<form action="//cphtechfest.us8.list-manage.com/subscribe/post?u=796fd984f9f18221643274d8f&amp;id=306795a525" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
   <div id="mc_embed_signup_scroll">
    
<div class="indicates-required"><span class="asterisk">*</span> indicates required</div>
<div class="mc-field-group">
    <label for="mce-EMAIL">Email Address  <span class="asterisk">*</span>
</label>
    <input type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>

    <div id="mce-responses" class="clear">
        <div class="response" id="mce-error-response" style="display:none"></div>
        <div class="response" id="mce-success-response" style="display:none"></div>
    </div>    
   <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_796fd984f9f18221643274d8f_306795a525" tabindex="-1" value=""></div>
   <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
   </div>
</form>
</div>

<script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[2]='LNAME';ftypes[2]='text';}(jQuery));var $mcj = jQuery.noConflict(true);</script>
